
services: {}

include:
  - ./docker/user-service.yml
  - ./docker/order-service.yml
  - ./docker/product-service.yml
  - ./docker/notification-service.yml
  - ./docker/databases/mysql-user.yml
  - ./docker/databases/mysql-product.yml
  - ./docker/databases/mysql-order.yml
  - ./docker/databases/mongo-notification.yml
  - ./docker/databases/redis.yml


volumes:
  mysql_user_data:
  mysql_product_data:
  mysql_order_data:
  mongo_data:
  redis_data:


# network where all services communicate
networks:
  app-network:
    driver: bridge



