version: "3.8"

services:
  inventory-service:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: inventory-service
    env_file:
      - .env
    ports:
      - "${SERVER_PORT}:8082"
    environment:
      DB_HOST: ${DB_HOST}
      DB_PORT: ${DB_PORT}
      DB_NAME: ${DB_NAME}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: ${DB_PASSWORD}

      RABBITMQ_HOST: ${RABBITMQ_HOST}
      RABBITMQ_PORT: ${RABBITMQ_PORT}
      RABBITMQ_USERNAME: ${RABBITMQ_USERNAME}
      RABBITMQ_PASSWORD: ${RABBITMQ_PASSWORD}
    depends_on:
      - inventory-postgres
    networks:
      - app-network

  inventory-postgres:
    image: postgres:16-alpine
    container_name: inventory-postgres
    restart: unless-stopped
    env_file:
      - .env
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
      - "${POSTGRES_PORT}:5434"
    volumes:
      - inventory_postgres_data:/var/lib/postgresql/data
    networks:
      - app-network

volumes:
  inventory_postgres_data:

networks:
  app-network:
    external: true
    name: app-network